# Generated by Django 3.1 on 2020-08-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='language',
            new_name='language_s',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='name_s',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='time',
            new_name='time_s',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='type',
            new_name='type_s',
        ),
    ]
