# Generated by Django 3.1 on 2020-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200826_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='imdb_url',
            field=models.CharField(max_length=300, verbose_name='IMDb链接'),
        ),
    ]
