# Generated by Django 3.1 on 2020-08-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200826_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='buy_url',
            field=models.CharField(max_length=128, verbose_name='购票链接'),
        ),
        migrations.AlterField(
            model_name='student',
            name='director',
            field=models.CharField(blank=True, max_length=128, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='student',
            name='language_s',
            field=models.CharField(blank=True, max_length=128, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='student',
            name='made',
            field=models.CharField(blank=True, max_length=128, verbose_name='制片国家/地区'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name_s',
            field=models.CharField(blank=True, max_length=128, verbose_name='电影名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nickname',
            field=models.CharField(max_length=128, verbose_name='又名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='run_time',
            field=models.CharField(max_length=128, verbose_name='片长'),
        ),
        migrations.AlterField(
            model_name='student',
            name='socre',
            field=models.CharField(max_length=128, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='student',
            name='time_s',
            field=models.CharField(blank=True, max_length=128, verbose_name='上映日期'),
        ),
        migrations.AlterField(
            model_name='student',
            name='type_s',
            field=models.CharField(blank=True, max_length=128, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='writers',
            field=models.CharField(blank=True, max_length=128, verbose_name='编剧'),
        ),
    ]
